- hosts: webserver 
  tasks:
          - name: "Installing APACHE Webserver software"
            package:
                  name: "httpd"
                  state: present

          - name: "Installing the PHP software"
            package:
                  name: "php"
                  state: present
         
          - name: "Copying the webpage to the webserver"
            copy:
                  dest: "/var/www/html/"
                  src: "/root/haproxy.php" 

          - name: "Starting firewall if not running"
            service:
                  name: "firewalld"
                  state: started
                  enabled: yes

          - name: "Creating firewall rule to expose the webserver on port no 80"
            firewalld:
                    port: "80/tcp"
                    state: enabled
                    permanent: yes
                    immediate: yes
                    
          - name: "Starting webserver services"
            service:
                  name: "httpd"
                  state: started


- hosts: 127.0.0.1
  vars:
          exposed_port: 8080

  tasks:
          - name: "Installing HAproxy Software"
            package:
                  name: "haproxy"
                  state: present

          - name: "Configuring HAProxy coonfiguration file"
            template:
                    src: "/root/haproxy.cfg"
                    dest: "/etc/haproxy/haproxy.cfg"
            register: config

          - name: " Starting Haproxy services"
            service: 
                   name: "haproxy"
                   state: started
                   enabled: yes
            when: config.changed == false

          - name: " Staring the firewall if not started"
            service: 
                    name: "firewalld"
                    state: started
                    enabled: yes

          - name: " Creating firewall rule for Haproxy on port no {{ exposed_port }}"
            firewalld:
                    port: " {{ exposed_port}}/tcp "
                    permanent: yes
                    state: enabled
                    immediate: yes
            
           - name: "Restarting  the Haproxy services"
            service: 
                    name: "haproxy"
                    state: restarted
                    enabled: yes
            when: config.changed == true




