- hosts: webserver
  tasks:
   - name: "Installing Apache Webserver"
     package:
      name: "httpd"
   - name: "Installing PHP software"
     package:
      name: "php"
   - name: "Copying the webpage to webserver"
     copy:
      dest: "/var/www/html/"
      src: "/web/haproxy.php"
   - name: "Creating firewall rule to expose the webserver on port 80"
     firewalld:
      port: "80/tcp"
      state: enabled
      permanent: yes
      immediate: yes
   - name: "Starting webserver service"
     service:
      name: "httpd"
      state: started     
